---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/stwomack/pcf-ers-demo.git
    branch: master

- name: cf
  type: cf
  source:
    api: https://api.run.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: test-build-deploy
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/ci/tasks/build.yml
  - put: cf
    params:
      current_app_name: my-demo
      manifest: source-code/manifest.yml
      path: build-output/pcf-ers-demo-0.0.1-SNAPSHOT.jar